export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
export MAD_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/source
export PETSC_ROOT=/Users/fgalarce/home/01_research/MAD/source/ci/petsc
alias mpirun=/Users/fgalarce/home/01_research/MAD/source/ci/petsc/build/bin/mpirun
alias mad=cd /Users/fgalarce/home/01_research/MAD/source/ci/source
